/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bd37502f-e818-4222-b270-0aea52008108",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SoIfI6LQu",
    "aws_user_pools_web_client_id": "1r7ha4fdpakkogqnjd3dvh7j0t",
    "oauth": {
        "domain": "peticofirstyfe1cf8eb-fe1cf8eb-local.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://",
        "redirectSignOut": "myapp://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
